"""
A simple Hello World plugin to test the plugin system.
"""

PLUGIN_SCHEMAS = [
    {
        "type": "function",
        "function": {
            "name": "hello_plugin",
            "description": "A test plugin that returns a greeting. Use this to verify the plugin system works.",
            "parameters": {
                "type": "object",
                "properties": {
                    "name": {"type": "string", "description": "Name to greet"}
                },
                "required": ["name"],
            },
        },
    }
]


def hello_plugin(name: str) -> str:
    return f"Hello, {name}! This greeting was generated by a dynamically loaded plugin from ~/.yolo/plugins."
